FROM php:8.2-apache
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions pdo mysqli pdo_mysql zip

RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
    mv composer.phar /usr/local/bin/composer

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN apt update && apt install -yqq nodejs npm

COPY . /var/www/

RUN chmod a+rwx -R /var/www
COPY ./docker/apache.conf /etc/apache2/sites-available/000-default.conf
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN cd /var/www  && composer install && npm install --force && npm run build

WORKDIR /var/www/
ENTRYPOINT [ "bash", "./docker/docker.sh"]
EXPOSE 80